[build]
command = "npm run build"
publish = "_site"
functions = "functions"

[build.environment]
# Change this path with the path to your repository
GO_IMPORT_PATH = "github.com/LasEmil/frontendmasters-serverless"
